### PR TITLE
Fix corridor corner and placing condition bugs

### LINKED ISSUE #104: Corner creating bug
image

### LINKED ISSUE #107: Check for working place condition

### PR DESCRIPTION
**Pull request by Kiuh**
Closes #104 
Closes #107

### CODE REVIEW

File: JamGame/Assets/Scripts/TileUnion/Tile/TileImpl.cs [hunk 1]
```diff
@@ -210,12 +207,9 @@ private CornerType ChooseCornerForCorridor(WallType[] walls)
...
                 (true, _, _, true) => CornerType.Inside,
-                (true, _, true, _) => CornerType.WallRight,
-                (_, true, _, true) => CornerType.WallLeft,
-                (_, true, true, _) => CornerType.OutsideMiddle,
-                (true, true, _, _) => CornerType.OutsideRight,
-                (_, _, true, true) => CornerType.OutsideLeft,
-                _ => CornerType.None,
+                (true, _, _, _) => CornerType.WallRight,
+                (_, _, _, true) => CornerType.WallLeft,
+                (false, _, _, false) => CornerType.OutsideMiddle,
```
Comment (mertwole) [inline JamGame/Assets/Scripts/TileUnion/Tile/TileImpl.cs:212]: It's less general than previous approach. Also remove duplication in this method and `ChooseCorner`

**Review by mertwole — CHANGES_REQUESTED** [review]

File: JamGame/Assets/Scripts/TileUnion/Tile/TileImpl.cs [hunk 2]
```diff
@@ -302,21 +298,27 @@ public enum WallType
...
             return wallType == WallType.None || wallType == WallType.Door;
         }
 
-        public static bool IsWall(this WallType wallType)
-        {
-            return wallType != WallType.None;
-        }
-
-        public static bool IsWallForCorridor(this WallType wallType)
+        public static bool IsWall(this WallType wallType, DecideType decideType)
```
Comment (mertwole) [inline JamGame/Assets/Scripts/TileUnion/Tile/TileImpl.cs:314]: This too

File: JamGame/Assets/Scripts/TileUnion/Tile/TileImpl.cs (hunk 1 above)
Comment (mertwole) [reply JamGame/Assets/Scripts/TileUnion/Tile/TileImpl.cs]: Discussed
